#ifndef CELL_H
#define CELL_H

#include "bms_types.h"

typedef struct battery_cell {
    float voltage;
    float current;
    float temp;
    float state_of_charge;
    BMS_State state;
} Cell;

/*

 * Gets the current measurements of the cell.

 * In simulation, the values are generated by software.

 * Later, this will interface with actual sensors when implemented with STM32.

 */

Cell get_cell_data(void);

/*

 * Updates cell parameters based on current conditions.

 * Updates values such as SOC and temperature.

 */

void update_cell(Cell *cell);

#endif